apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-config
  namespace: default
data:
  DB_USER: "postgres"
  DB_PASS: "postgres"
  JWT_SECRET: "ember-oak-secret-change-in-production"
  USER_DB_NAME: "restaurant_users"
  MENU_DB_NAME: "restaurant_menu"
  ORDER_DB_NAME: "restaurant_orders"
  RES_DB_NAME: "restaurant_reservations"
